import {useState} from "react";
import Head from 'next/head'
import Advantages from "./components/Advantages/Advantages";
import Header from "./components/Header/Header";
import Video from "./components/Video/Video";
import Catalog from "./components/Catalog/Catalog";
import Faq from "./components/Faq/Faq";
import News from "./components/News/News";

function App({initialProdData, initialNewsData}) {

    const [isModalOpen, setIsModalOpen] = useState(false)

    return (
        <div className='App'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Video
                id='qHmB8mZdWBA'
                isModalActive={isModalOpen}
                setIsModalOpen={setIsModalOpen}
            />
            <Advantages/>
            <Catalog initialData={initialProdData}/>
            <Faq/>
            <News initialNewsData={initialNewsData}/>
        </div>
    )
}

export async function getStaticProps() {
    // mok data generator
    const genProdDataArr = count => {
        const result = []
        for (let i = 0; i < count; i++) {
            const options = []
            let counter = 0;
            for (let x = 0; x < count; x++) {
                options.push({
                    id: x + 1,
                    image: 'room_lq',
                    title: `Разработка макета рамки #${x + 1}`,
                    price: 17000 + counter,
                    isChecked: false,
                })
                counter += 100
            }
            result.push({
                id: i + 1,
                title: ' Фотобудка с ширмой',
                subtitle: '2м x 1.5м x 2 м',
                images: ['room', 'room', 'room', 'room', 'room'],
                options,
                price: 17000, // rub
                totalTime: 1 // hour
            })
        }
        return result
    }
    const genNewsDataArr = count => {
        const result = []
        for (let i = 0; i < count; i++) {
            result.push({
                id: i + 1,
                category: 'Фотобудка',
                date: JSON.stringify(new Date()),
                images: ['man', 'photo', 'man', 'photo', 'photo'],
                title: ' Фотобудка с ширмой',
                shortText: 'У нас есть широчайший ассортимент фотобудок на все случаи жизни',
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
            })
        }
        return result
    }

    const initialProdData = genProdDataArr(2)
    const initialNewsData = genNewsDataArr(20)

    return {
        props: {initialProdData, initialNewsData}
    }
}

export default App