import {useState} from "react";
import Head from 'next/head'
import Advantages from "./components/Advantages/Advantages";
import Header from "./components/Header/Header";
import Video from "./components/Video/Video";
import Catalog from "./components/Catalog/Catalog";

function App({initialData}) {

    const [isModalOpen, setIsModalOpen] = useState(false)

    return (
        <div className='App'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Video
                id='qHmB8mZdWBA'
                isModalActive={isModalOpen}
                setIsModalOpen={setIsModalOpen}
            />
            <Advantages/>
            <Catalog initialData={initialData}/>
        </div>
    )
}

export async function getStaticProps() {
    // mok data generator
    const genDataArr = count => {
        const result = []
        for (let i = 0; i < count; i++) {
            const options = []
            let counter = 0;
            for (let x = 0; x < count; x++) {
                options.push({
                    id: x + 1,
                    image: 'room_lq',
                    title: `Разработка макета рамки #${x + 1}`,
                    price: 17000 + counter,
                    isChecked: false,
                })
                counter += 100
            }
            result.push({
                id: i + 1,
                title: ' Фотобудка с ширмой',
                subtitle: '2м x 1.5м x 2 м',
                images: ['room', 'room', 'room', 'room', 'room'],
                options,
                price: 17000, // rub
                totalTime: 1 // hour
            })
        }
        return result
    }

    const initialData = genDataArr(20)
    return {
        props: {initialData}
    }
}

export default App